#include <syslog.h>  

int main(int argc, char **argv)  
{  
    openlog("MyLog", LOG_CONS | LOG_PID, LOG_LOCAL2);  
    syslog(LOG_INFO,  
           "This is a syslog test message generated by program '%s'\n",  
           argv[0]);  
    closelog();  
    return 0;  
}  
